version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "3002:3000"  # Changed the host port to 3002 to avoid conflicts
    volumes:
      - ./server:/app
    environment:
      NODE_ENV: development
    depends_on:
      - mongo
  client:
    build:
      context: ./client
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
    environment:
      NODE_ENV: development
    stdin_open: true
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
